# Full app config reference: https://fly.io/docs/reference/configuration/
app = "cdn-2025-02-25"
# Closest to the origin
primary_region = "iad"

kill_signal = "SIGTERM"
kill_timeout = 30

[env]
# This leaves 20% headroom from the machine's total available memory
# Any less than this and Varnish makes the machine crash due to OOM errors.
VARNISH_SIZE = "6400M"

[[vm]]
size = "performance-1x"
memory = "8GB"

[deploy]
strategy = "bluegreen"

[[services]]
internal_port = 9000
protocol = "tcp"

[[services.http_checks]]
grace_period = "5s"
interval = "5s"
method = "get"
path = "/health"
protocol = "http"
timeout = "3s"

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.ports]]
handlers = ["http"]
port = "80"

[services.concurrency]
hard_limit = 2500
soft_limit = 2000
type = "connections"
