# vim: set tabstop=4 shiftwidth=4 expandtab:

import '../../just/_config.just'
import '../../just/_config_fly.just'
import '../../just/fly.just'

[private]
default:
    @just --list

[private]
fmt:
    just --fmt --check --unstable
    just --version
